version: "3.5"

services:
  api01:
    &api
    image: gitlucaslima/quarkus-dguerra:4.0
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.85"   # Distribuir 1 unidade de CPU para api01
          memory: "180MB" # Distribuir 250MB de memória para api01
    networks:
      - default

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"   # Distribuir 0.5 unidades de CPU para nginx
          memory: "05MB" # Distribuir 50MB de memória para nginx

  db:
    image: mongo
    hostname: db
    ports:
      - "27018:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: "0.75"   # Distribuir 0.5 unidades de CPU para db
          memory: "185MB" # Distribuir 200MB de memória para db

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
