version: "3.5"

services:
  api01:
    &api
    image: gitlucaslima/quarkus-api
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  db:
    image: mongo
    hostname: db
    ports:
      - "27018:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
