version: "3.5"

services:
  api01:
    &api
    image: gitlucaslima/quarkus-dguerra:4.0
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.525"
          memory: "200MB"
    networks:
      - default

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    networks:
      - default


  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"

  db:
    image: mongo
    hostname: db
    ports:
      - "27018:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160MB"
    networks:
      - default

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
